# Generated by Django 5.1.1 on 2024-09-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('fresh', models.BooleanField()),
                ('stock', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('classification', models.CharField(choices=[('EX', 'Extra'), ('1ST', 'Primeira'), ('2ND', 'Segunda'), ('3RD', 'Terceira')], max_length=3)),
            ],
        ),
    ]
